server {
    listen 80;
    server_name _;

    root /var/www/laravel/public;
    index index.php;

    access_log /var/log/nginx/track-access.log;
    error_log /var/log/nginx/track-error.log;

    location / { 
        try_files $uri $uri/ /index.php?$query_string; 
    } 

    location ~ \.php$ {
        fastcgi_pass laravel_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /api/ { 
        proxy_pass http://fastapi:8000; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
    }

    error_page 404 /404.html;

    # listen 443 ssl; # managed by Certbot
    # ssl_certificate /etc/letsencrypt/live/name.ai-info.ru/fullchain.pem; # managed by Certbot
    # ssl_certificate_key /etc/letsencrypt/live/name.ai-info.ru/privkey.pem; # managed by Certbot
    # include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # add_header Strict-Transport-Security "max-age=31536000" always;

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}