CREATE DATABASE IF NOT EXISTS tracker_db 
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 

GRANT ALL ON tracker_db.* TO 'odoo'@'%';
FLUSH PRIVILEGES;

USE tracker_db;
CREATE TABLE habbits ( 
    id BIGINT PRIMARY KEY AUTO_INCREMENT, 
    habbit TEXT NOT NULL, 
    body TEXT NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 